DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS gift_certificate;
DROP TABLE IF EXISTS tag_has_gift_certificate;

CREATE TABLE IF NOT EXISTS tag
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS gift_certificate
(
    ID             BIGINT(100)   NOT NULL AUTO_INCREMENT,
    NAME           VARCHAR(200)  NOT NULL,
    DESCRIPTION    VARCHAR(1000) NOT NULL,
    PRICE          DECIMAL(7, 2) NOT NULL,
    CREATEDATE     DATETIME      NOT NULL,
    LASTUPDATEDATE DATETIME      NOT NULL,
    DURATION       INT           NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS tag_has_gift_certificate
(
    TAG_ID              BIGINT(100) NOT NULL,
    GIFT_CERTIFICATE_ID BIGINT(100) NOT NULL
);